### ISSUE TITLE
whither `angle`?

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#111]
Tangram JS supports an undocumented `angle` parameter when drawing `point` geometries, but ES currently doesn't – per https://github.com/tangrams/tangram-es/issues/551, has the fate of this feature been decided, either _de jure_ or _de facto_?

cc @blair1618

**Comment by matteblair** [comment]
Right, so, to recap: the problem with a single parameter called "angle" is that it doesn't specify what coordinate system the angle refers to. Specifically, it's ambiguous whether the angle is relative to world space (the cardinal directions on the map) or screen space (the axes of your window), and there are circumstances where both are appropriate. 

The best solution I can come up with is to add another parameter: a boolean flag that specifies whether the geometry should be treated as a "billboard" (which rotates in screen space) or a "sticker" (which rotates in world space). For example:

``` yaml
icons:
  sprite: location-gem
  billboard: false
  angle: global.bearing
```

would create an icon rotated by the amount `global.bearing` in _world space_ (units and signs of angles is a separate discussion), and

``` yaml
icons:
  sprite: train
  billboard: true
  angle: global.icon_tilt
```

would create an icon rotated by the amount `global.icon_tilt` in _screen space_.
