### ISSUE TITLE
deprecate 'inline object' textures in the scene file

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#112]
https://github.com/tangrams/tangram/commit/18d79786c4d3fccc24be967a6058d2fdb74c04b1

**Comment by meetar** [comment]
…in fact I could use a review of the entire textures page, not sure all of those examples are working properly. eg:

``` yaml
styles:
    points:
        texture: images/ghost.png
```

Was naming a url as the value of a texture key like this ever valid?
