### ISSUE TITLE
stroke parameters

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-docs#118]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#stroke specifies `stroke` as an `Optional {color, width} or stops`

... But in https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#font-parameters

This example is given:

``` yaml
draw:
    text:
        font:
            family: Arial
            size: 14px
            style: italic
            weight: bold
            fill: '#cccccc'
            stroke: white
            transform: uppercase
```

Does `stroke` also take a plain color, or is the extant example egregiously erroneous?
