### ISSUE TITLE
Explain concepts behind ordering

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-docs#138]
Most people with a web background will be used to the ordering model of layers then an order within the layers. Tangram's is substantially different. There is relatively little documentation on Tangram's ordering or how it differs.

The [order](https://mapzen.com/documentation/tangram/draw/#order) mapping is documented as

> Applies to all _draw styles_. Sets the drawing order of the draw style, to be used in case of depth collisions. Higher-ordered layers will be drawn over lower-ordered layers. Child layers override parent layers.

Depth collisions are undefined, as is depth.

> Higher-ordered layers will be drawn over lower-ordered layers.

order is a property of [draw groups](https://mapzen.com/documentation/tangram/draw/#draw-group) which then belong to a layer or sublayer. Layers are part of the layers element which is a YAML mapping, so layers have no YAML order.

When rendering from [MVT](https://github.com/mapbox/vector-tile-spec) there are two additional orders: layer order within the tile and feature order within a layer. How do these come into play?

I would expect the overall order to be draw order, layer order, then feature order but I can find nothing documenting this.

**Comment by meetar** [comment]
Thanks for this feedback – I'll use this thread to track the changes I make to address the issue, starting with: https://github.com/tangrams/tangram-docs/commit/a371101bf5703d3ec4af48a0871a7687088ab05f

**Comment by pnorman** [comment]
With some testing with lines coming from the same MVT layer and the same tangram order I found out that the top-most object is the is one which comes first in the MVT ordering, the **reverse** of expectations.

E.g. normally in a roads layer you'd want "high value" roads to [to the end in an ascending sort](https://github.com/gravitystorm/openstreetmap-carto/blob/v2.42.0/project.yaml#L1048-L1058). This is reflected in the osm2pgsql z_order [which puts motorways high](https://github.com/openstreetmap/osm2pgsql/blob/0.90.0/tagtransform.cpp#L44-L54) so they will be at the end of a layer if that layer sorts by z_order. This is because conventional algorithms draw the first object in the layer first and later ones on top of it.

Tangram requires the **reverse** of this.

**Comment by pnorman** [comment]
Another factor that comes into ordering is the name of the styles.

If I have

``` yaml
styles:
    z:
        base: lines
        dash: [2, 2]
        dash_background_color: blue
layers:
    roads:
        data: { source: mapzen }
        draw:
            lines:
                order: 2
                color: green
                width: 14
            z:
                order: 2
                color: black
                width: 6
```

I get a different result if I change the name of the style object to "a"
![image](https://cloud.githubusercontent.com/assets/1190866/17910982/4d2fc662-6940-11e6-95bf-ca5858dbd7a7.png) with z and 
![image](https://cloud.githubusercontent.com/assets/1190866/17910992/5f42a8f6-6940-11e6-899b-5f2d74d2bb34.png) with a.
