### ISSUE TITLE
Document `buffer` parameter for points and text styles

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-docs#141]
`points` and `text` styles (i.e. those that perform collision) have an optional `buffer` property, which is not currently documented.

`buffer` specifies an optional buffer area that expands the collision bounding box of the feature, to avoid features from being rendered closer to either other than desired. By default, there is no `buffer`, meaning that features are allowed to exactly touch (but not overlap).

`buffer` is specified in pixels (`px`) and can be either:
- A single value, which uniformly buffers the feature on all sides.
  - `buffer: 2px`: create a two-pixel buffer on each side of the feature.
- A two-element array specifying separate _horizontal_ and _vertical_ buffering values:
  - `buffer: [2px, 1px]`: creates a two-pixel buffer on the _left_ and _right_ sides of the feature, and a one-pixel buffer on its _top_ and _bottom_.

For `text` attached to `points`, the `buffer` can be _independently_ specified (or omitted) for each, e.g.:

```
draw:
  points:
    buffer: 1px # point portion has a one-pixel buffer
    ...
    text:
      buffer: 2px # text portion has a two-pixel buffer
      ...
```
