### ISSUE TITLE
Clarify text options around collisions

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-docs#177]
In the https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#text-behavior section we talk about **collisions**, but the current released behavior doesn't seem to match the docs. Instead I need to set `optional: true` to allow the point to always appear, and make the text attachment optional.

(I think the released behavior is correct, it's the docs that need updating.)

```
import: https://mapzen.com/carto/refill-style/refill-style.yaml

sources:
    trees:
        type: GeoJSON
        url: https://s3.amazonaws.com/mapzen-assets/images/dot-mapping/trees_min.geojson

styles:
    _tree_icons_style:
        base: points
        blend_order: 1
        texture: https://s3.amazonaws.com/mapzen-assets/images/dot-mapping/tree_white.png

layers:
    _trees_layer:
        data: { source: trees }
        filter: { $zoom: { min: 12 } }
        draw:
            points:
                color: [[12, [0.290, 0.604, 0.290, 0.30]], [18, [0.165, 0.478, 0.165, 0.85]]] 
                size: [[12, 1px], [15, 5px], [18, 14px], [18, 20px], [22, 52px]]
                collide: false
        _trees_icon_sublayer:
            filter: { $zoom: { min: 18 } }
            draw:
                _tree_icons_style:
                    size: [[18, 14px], [22, 40px]]
                    collide: false
                points:
                    text:
                        text_source: |
                            function () {
                                return feature.qSpecies.split(':: ')[1];
                            }
                        font:
                            fill: forestgreen
                            size: 10pt
                            stroke:
                                width: 5px
                                color: white
                        optional: true
                        #collide: false     # if I set collide false then my green dots disappear 

    roads:
        filter: { $zoom: { min: 18} }
```
