### ISSUE TITLE
Document MBTiles sources for tangram-es

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#192]
Initial support added in: https://github.com/tangrams/tangram-es/pull/1015

**Comment by tallytalwar** [comment]
This documentation should cover the usage in specific platforms, example when using an absolute path in android, one will need `READ_EXTERNAL_STORAGE` permission both in android manifest and at runtime using the following:
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
           requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, 1);
}
```

**Comment by nvkelso** [comment]
From @matteblair's comment on https://github.com/tangrams/tangram-es/pull/1015#issuecomment-278452805:

> The scene file now supports only read-only MBTiles sources using existing files. When the `url` of a `sources` entry ends with the `.mbtiles` extension, it is recognized as an MBTiles source. The `type` field remains unchanged, that is it should be set to the type of vector or raster tile expected from the data source. For example:

```yaml
sources:
  _savedTiles: #This is an example MBTiles data source.
    type: TopoJSON #We expect TopoJSON data from the source.
    url: /path/to/my/file.mbtiles #Relative and absolute file paths supported
    max_zoom: 16 #Other optional parameters are applied as usual.
```

**Comment by tallytalwar** [comment]
Kind a outdated. There is no restriction on the path to mbtiles resource to be an absolute path.

**Comment by nvkelso** [comment]
Updated my comment :)

**Comment by filip-kinsky** [comment]
Is there any docs on how to assemble the MBTiles file in appropriate format? I tried few combinations like https://openmaptiles.org/downloads , https://mapzen.com/data/metro-extracts/ , Mapbox Studio Classic, https://github.com/mapbox/tippecanoe but didn't get MBTiles file to render in Android app yet.

**Comment by saeedtabrizi** [comment]
@matteblair , @Buthrakaur  , I have same issue on **Android** .
i can't render via following scene configuration :+1: 
```
osm_offline1:
        type: MVT
        url: /storage/emulated/0/demo.mbtiles
        max_zoom: 14  
```
or there is a undocumented feature or configuration to load and render **.mbtiles** in android .
Please write a sample here 
Thanks .
