### ISSUE TITLE
Interaction of layer 'visible' flag with sublayers is unspecified

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#198]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/layers.md

Example:
```yaml
layers:
  parent-layer:
    visible: false
    child-layer:
      visible: true
      draw:
        polygons:
          order: 1
          color: blue
```

Is `child-layer` drawn? The current documentation is ambiguous on this, and we've recently discovered that tangram-js and tangram-es resolve this differently: https://github.com/tangrams/walkabout-style/pull/154

cc @bcamper @nvkelso @meetar
