### ISSUE TITLE
'style' vs 'mix' in style configuration

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-docs#23]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/styles.md#style

In the absence of a `url` parameter, is

``` yaml
styles:
    toner:
        style: halftone
```

distinct from

``` yaml
styles:
    toner:
        mix: halftone
```

?
